name: countdown-bar
version: 0.0.1
github: "AndreiUlmeyda/countdown-bar"
license: MIT
author: "Adrian Schurz"
maintainer: "schurz.adrian@gmail.com"
copyright: "2021 Adrian Schurz"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/AndreiUlmeyda/countdown-bar#readme>

dependencies:
  - base >= 4.7 && < 5
  - gloss

default-extensions:
  - DerivingStrategies

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wmonomorphism-restriction
    - -Wimplicit-prelude
    - -Wmissing-local-signatures
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Widentities
    - -Wredundant-constraints
    - -Wpartial-fields
    - -Wall-missed-specialisations
    - -Wcpp-undef
    - -Wmissing-deriving-strategies
    - -Wunused-packages
    - -Wunused-type-patterns
    - -Wcompat
    - -Wsafe

executables:
  countdown-bar:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - countdown-bar

tests:
  countdown-bar-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - countdown-bar
